### ISSUE TITLE
doschgpt.exe bin don't return any output

### ISSUE THREAD

**Issue by soviet9922** [yeokm1/doschgpt#1] opened 2023-03-26 23:03 UTC
Tested the release file doschgpt.exe on a IBM 5155 similar setup to you using dos 5.0
Has mtcp already set up and working previously.

Configured the .ini file changed the ip address and set my key for chatgpt, run the proxy on my pc.

The issue is when try to run the provided binary chatgpt.exe nothing happens at all the cursor _ will blink and no output at all from the program. Tried the optional debug parameters but nothing happens after that have to do ctrl+alt+del pressing esc or control+c etc will do nothing.

Theres any error codes the software should return or something?

**Comment by yeokm1** [comment] 2023-03-27 02:18
I have never experienced this issue so far. Not sure if there is a problem but I used DOS 6.22 only. I didn't program any special error handling as this is meant to be a toy project.

It's challenging for me to debug this remotely without access to your machine. Can u take some screenshots or short video? And if you can, screenshots of your MTCP setup and DHCP result. Also also do verify the binary is downloaded correctly.

**Comment by soviet9922** [comment] 2023-03-27 03:34
Tested the program on a generic 8088 system and got the same results (using dos 5.0).
And now checked on a 386 using dos 6.22 and works perfectly fine.
Will do some more tests and send you some videos tomorrow.

Regards.

**Comment by yeokm1** [comment] 2023-03-27 04:44
Hmmm.. It shows I need to do more testing on older DOS versions hah!

Thanks for your assistance!

**Comment by Maillouski** [comment] 2023-03-28 11:09
Quick questions for the others with the issue. Are your 640kb of memory all on the motherboard or some is on an ISA card?

My Compaq Portable has the same issue. The program just freeze. Maybe the difference compared to the IBM 5155 is the addon memory card. 

It would be super-nice to have this bug resolved for VCF East on April 14th. I am exhibiting my Compaq Portable and having ChatGPT would make a very good interactive booth.

**Comment by yeokm1** [comment] 2023-03-28 11:21
For my IBM5155, all the 640kb is on the main motherboard. 

It would help to have more information, such as but not limited to

- Machine Model
- CPU used
- DOS version
- RAM amount and in what arrangement
- Config.sys and autoexec.bat files
- Perhaps the ISA cards you have installed in your system.

With this information, I can try to replicate your configuration using emulators like DOSBOX-X or 86box.

And for the DOS machines that this app manages to work on, what are their specifications and configurations so I can narrow the root cause.

My next newer machine is a 486 already and it works. I don't have any other retro machines of the 8088 class, so it's challenging for me to replicate this but I'll try to with emulators.

**Comment by Maillouski** [comment] 2023-03-28 11:52
My machine:
Compaq Portable 1
DOS 6.22
Config.Sys is empty
8088 cpu
256kb onboard memory 
384kb on a Sixpack Plus ISA card
It has a MFM HDD Controller card
3Com 3C509B-TPO ethernet adapter
The factory video card
Floppy Controller card

I also have an IBM 5150 desktop on which I can test. It has 256kb on-board memory. XT-IDE card and a VGA card.

**Comment by yeokm1** [comment] 2023-03-28 12:00
> My machine: Compaq Portable 1 DOS 6.22 8088 cpu 256kb onboard memory 384kb on a Sixpack Plus ISA card It has a MFM HDD Controller card 3Com 3C509B-TPO ethernet adapter The factory video card Floppy Controller card
> 
> I also have an IBM 5150 desktop on which I can test. It has 256kb on-board memory. XT-IDE card and a VGA card.

Thanks for your information. I'll try to replicate your setup on 86box. (I should have checked on 86box instead of just Virtualbox before releasing.)

I have a hunch too this could be a memory problem.

Do come back to me on your test result on your IBM 5150

**Comment by yeokm1** [comment] 2023-03-28 15:25
@Synoptic2 

I have tried the following in 86Box:

* Compaq Portable
* Intel 8088 at 4.77Mhz
* 256KB onboard RAM
* ISA Compaq CGA card
* XT/IDE Controller
* IDE hard drive
* Magitronic B215 Floppy Controller
* 2x 1.44MB floppy
* AST SixPakPlus with 384K RAM starting at 256KB address
* DOS 6.22

I can't seem to emulate the MFM disk and no network cards in 86Box.

![image](https://user-images.githubusercontent.com/1570592/228284714-3a3ad0d4-7adc-401f-8a9c-d1ad22ad75d6.png)
![image](https://user-images.githubusercontent.com/1570592/228284913-04cdab36-85fa-42e2-a604-40649e94e3c0.png)
![image](https://user-images.githubusercontent.com/1570592/228284968-8154045b-7ce1-49af-87e1-9fc5f9a95324.png)
![image](https://user-images.githubusercontent.com/1570592/228285125-73183570-35e1-435f-9b7d-0c08023406ec.png)

I cannot simulate the problem at all :( .

The variable I'm missing is your config.sys and autoexec.bat configurations. Can you put it here for me to check?

At the same time, I need your help by having empty (or just comment using rem) config.sys and autoexec.bat configurations . No memory managers (if you have one), no startup programs, no (packet) drivers and the bare minimum of paths. And just launch the binary. See if it's able to start. You should see something like this.

![image](https://user-images.githubusercontent.com/1570592/228283643-f5c0791d-4d76-4257-a2de-4f26a5f4cf5f.png)

If it can start, will need to know which line is causing it. If it still cannot start, at least this gives me a minimum baseline and reduced variability I can work with.

**Comment by Maillouski** [comment] 2023-03-28 15:42
I will do it later today. Btw, I see you're flying a plane. I'm PPL SEL IFR :)

**Comment by yeokm1** [comment] 2023-03-28 16:32
@Synoptic2 Thanks! I'm an FAA PPL ASEL only haha. Working on my IFR or more is something I can probably do in the longer term.

**Comment by Maillouski** [comment] 2023-03-28 18:41
I tested by making a floppy boot disk.
NO config.sys
NO autoexec.bat

I ALSO removed the SixPack Plus AND the ethernet card from the COMPAQ and I get the same behaviour.
I know the processor was manufactured by AMD, but that should not make a difference as at the time, they were a fab and not a CPU designer in competition with Intel.

Same issue with my IBM 5150 in the same conditions.

Green Screen is the COMPAQ
BLACK/WHITE is the IBM
![IMG_0892](https://user-images.githubusercontent.com/26332223/228362658-8115f153-79f4-415f-ad16-8207e98bef57.jpg)
![IMG_0891](https://user-images.githubusercontent.com/26332223/228336408-a3f7dfa5-88e2-44cd-b92e-d5078d9c8777.jpg)

**Comment by yeokm1** [comment] 2023-03-29 02:14
@Synoptic2 Brutman has informed me of an issue with the Compaq Portable with OpenWatcom programs.

![image](https://user-images.githubusercontent.com/1570592/228407887-c162f51a-4232-4501-9356-13096d8f423e.png)

I have patched the binary as per his instructions. Do give this a shot on your Compaq Portable.

[doschgpt-v0.2-a.zip](https://github.com/yeokm1/doschgpt/files/11095800/doschgpt-v0.2-a.zip)

This binary also includes another update to parse quotes " but it should not affect anything.

I know it does not explain why it does not work on the IBM 5150 but let me solve one issue at a time. Of course if you can, you can try this too on that PC.

You should see something like follows. In both cases, I pressed F5 on start to bypass everything in config.sys and autoexec.bat

![cp-port-2a](https://user-images.githubusercontent.com/1570592/228427678-3ff78adf-05bf-4a2d-9a8e-70547b711451.PNG)
![5150-2a](https://user-images.githubusercontent.com/1570592/228427690-50b65254-2115-401f-b333-12a4bc424434.PNG)

**Comment by Maillouski** [comment] 2023-03-29 13:25
Bad news. Same behaviour on both PC. I doublechecked I had the right binary. Booting off a floppy on DOS 6.22 without autoexec.bat or Config.sys.

![IMG_0894](https://user-images.githubusercontent.com/26332223/228552494-82791751-f77a-415b-ae93-5862fb6454b9.jpg)

**Comment by yeokm1** [comment] 2023-03-29 15:00
Hi @Synoptic2 

Let me get back to basics. I have included many binary builds of hello world programs of different memory models and patches combinations plus a newer Watcom 2.0 beta compiler. I would like to trouble you to execute them on both your machines and report the results. 

This will help me to verify which compile configurations could be an issue. If you have any other newer vintage machines like 286 or 386, it would help if it can be tested there as well. 

All builds below are still linked with MTCP object files.

Compiled with Watcom 1.9
* 9hw-c.exe: Hello World Compact Model
* 9hw-c-p.exe: Hello World Compact Model patched for Compaq Portable
* 9hw-l.exe: Hello World Large Model
* 9hw-l-p.exe: Hello World Large Model patched for Compaq Portable

Compiled with Watcom 2.0 beta
* 2hw-c.exe: Hello World Compact Model
* 2hw-l.exe: Hello World Large Model
* 2gp-l.exe: DOS Chat GPT Large Model

Also if you are amenable, I would suggest a direct message and/or Zoom call session to more easily facilitate communication instead of back-and-forth through this issue page.

You can text me via any of those channels:

* https://www.facebook.com/yeokhengmeng
* https://twitter.com/yeokm1
* https://www.linkedin.com/in/yeokhengmeng/
* Telegram: yeokm1 

I'm really committed to find out the cause of this issue if I can within my abilities and personal time.

**For anyone else looking at this issue, would appreciate any input as well such as which platform is working or not working.**

[binaries.zip](https://github.com/yeokm1/doschgpt/files/11102287/binaries.zip)

**Comment by Maillouski** [comment] 2023-03-29 15:46
I will test on both 8088 machines AND on my trusty 80486 too.

**Comment by yeokm1** [comment] 2023-03-29 15:50
> I will test on both 8088 machines AND on my trusty 80486 too.

Thanks a lot. 😄  So far I cannot replicate this issue on my [IBM5155](https://github.com/yeokm1/retro-configs/tree/master/desktops/ibm-5155), my [486 machine](https://github.com/yeokm1/retro-configs/tree/master/desktops/generic-486-pc), [Virtualbox DOS 6.22](https://github.com/yeokm1/retro-configs/tree/master/vms/vbox-dos622), 86Box simulating original IBM PC and Compaq Portable. Tough nut to crack.

**Comment by Synoptic2** [comment] 2023-03-29 15:51
Check your FB.

**Comment by Maillouski** [comment] 2023-03-29 16:13
I tested all 7 binaries, and they all work on my 486, Compaq and IBM 5150. I get an Hello World or an output saying doschgpt.ini is not found with some text

**Comment by mbbrutman** [comment] 2023-03-29 17:22
soviet9922 - if you have mTCP already running then you might have used the debug trace before.  If not, the instructions are in the PDF.  Here is the short version:

- SET DEBUGGING=0x80FF
- SET LOGFILE=TRACE.LOG
- run the program
- reboot, run chkdsk to be safe, and then send the TRACE.LOG file for analysis.  It might give a hint as to what is going wrong.

**Comment by Maillouski** [comment] 2023-03-30 00:35
SUCCESS using 2GP-L.EXE on COMPAQ Portable and IBM 5150
![18F0F0CA-B082-42CF-8EC3-3C07BBA901AC](https://user-images.githubusercontent.com/26332223/228698223-e0292717-ec8c-466e-a3fa-86464da73a82.jpeg)

**Comment by yeokm1** [comment] 2023-03-30 07:09
@soviet9922 @Synoptic2 Please use the updated release . https://github.com/yeokm1/doschgpt/releases

**Closed as completed by yeokm1** 2023-03-30 07:09 UTC
